name: Publish package
on:
  push:
    branches: [ 'latest', 'develop' ]
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: '17'
          java-distribution: 'adopt'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Publish client
        run: mvn -T 4 --batch-mode deploy -q -s settings.xml
        env:
          REPO_USERNAME: github-deploy
          REPO_PASSWORD: ${{ secrets.DEPLOY_TOKEN }}
      - name: Upload Social to Maven Central
        run: mvn -T 4 --batch-mode clean install -q -s settings.xml
        env:
          REPO_USERNAME: github-deploy
          REPO_PASSWORD: ${{ secrets.DEPLOY_TOKEN }}