// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.23.4
// source: servers.proto

package gsms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GSMSService_RegisterListenerGame_FullMethodName  = "/org.nethergames.gsms.rpc.GSMSService/registerListenerGame"
	GSMSService_RegisterListenerProxy_FullMethodName = "/org.nethergames.gsms.rpc.GSMSService/registerListenerProxy"
)

// GSMSServiceClient is the client API for GSMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GSMSServiceClient interface {
	// For downstream servers to listen on changes, as well as providing server status in real-time.
	RegisterListenerGame(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdateModel, GameEvent], error)
	// Register proxy listener to listen on changes, and provide proxy status in real-time.
	RegisterListenerProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyModel, ServerEvent], error)
}

type gSMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGSMSServiceClient(cc grpc.ClientConnInterface) GSMSServiceClient {
	return &gSMSServiceClient{cc}
}

func (c *gSMSServiceClient) RegisterListenerGame(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[UpdateModel, GameEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GSMSService_ServiceDesc.Streams[0], GSMSService_RegisterListenerGame_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateModel, GameEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GSMSService_RegisterListenerGameClient = grpc.BidiStreamingClient[UpdateModel, GameEvent]

func (c *gSMSServiceClient) RegisterListenerProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyModel, ServerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GSMSService_ServiceDesc.Streams[1], GSMSService_RegisterListenerProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyModel, ServerEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GSMSService_RegisterListenerProxyClient = grpc.BidiStreamingClient[ProxyModel, ServerEvent]

// GSMSServiceServer is the server API for GSMSService service.
// All implementations must embed UnimplementedGSMSServiceServer
// for forward compatibility.
type GSMSServiceServer interface {
	// For downstream servers to listen on changes, as well as providing server status in real-time.
	RegisterListenerGame(grpc.BidiStreamingServer[UpdateModel, GameEvent]) error
	// Register proxy listener to listen on changes, and provide proxy status in real-time.
	RegisterListenerProxy(grpc.BidiStreamingServer[ProxyModel, ServerEvent]) error
	mustEmbedUnimplementedGSMSServiceServer()
}

// UnimplementedGSMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGSMSServiceServer struct{}

func (UnimplementedGSMSServiceServer) RegisterListenerGame(grpc.BidiStreamingServer[UpdateModel, GameEvent]) error {
	return status.Error(codes.Unimplemented, "method RegisterListenerGame not implemented")
}
func (UnimplementedGSMSServiceServer) RegisterListenerProxy(grpc.BidiStreamingServer[ProxyModel, ServerEvent]) error {
	return status.Error(codes.Unimplemented, "method RegisterListenerProxy not implemented")
}
func (UnimplementedGSMSServiceServer) mustEmbedUnimplementedGSMSServiceServer() {}
func (UnimplementedGSMSServiceServer) testEmbeddedByValue()                     {}

// UnsafeGSMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GSMSServiceServer will
// result in compilation errors.
type UnsafeGSMSServiceServer interface {
	mustEmbedUnimplementedGSMSServiceServer()
}

func RegisterGSMSServiceServer(s grpc.ServiceRegistrar, srv GSMSServiceServer) {
	// If the following call panics, it indicates UnimplementedGSMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GSMSService_ServiceDesc, srv)
}

func _GSMSService_RegisterListenerGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GSMSServiceServer).RegisterListenerGame(&grpc.GenericServerStream[UpdateModel, GameEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GSMSService_RegisterListenerGameServer = grpc.BidiStreamingServer[UpdateModel, GameEvent]

func _GSMSService_RegisterListenerProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GSMSServiceServer).RegisterListenerProxy(&grpc.GenericServerStream[ProxyModel, ServerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GSMSService_RegisterListenerProxyServer = grpc.BidiStreamingServer[ProxyModel, ServerEvent]

// GSMSService_ServiceDesc is the grpc.ServiceDesc for GSMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GSMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.nethergames.gsms.rpc.GSMSService",
	HandlerType: (*GSMSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "registerListenerGame",
			Handler:       _GSMSService_RegisterListenerGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "registerListenerProxy",
			Handler:       _GSMSService_RegisterListenerProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "servers.proto",
}
