// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: locater.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerLocality_AddPlayer_FullMethodName       = "/org.nethergames.social.rpc.PlayerLocality/addPlayer"
	PlayerLocality_RemovePlayer_FullMethodName    = "/org.nethergames.social.rpc.PlayerLocality/removePlayer"
	PlayerLocality_UpdatePlayer_FullMethodName    = "/org.nethergames.social.rpc.PlayerLocality/updatePlayer"
	PlayerLocality_GetPlayer_FullMethodName       = "/org.nethergames.social.rpc.PlayerLocality/getPlayer"
	PlayerLocality_GetPlayerByXuid_FullMethodName = "/org.nethergames.social.rpc.PlayerLocality/getPlayerByXuid"
	PlayerLocality_GetPlayerByName_FullMethodName = "/org.nethergames.social.rpc.PlayerLocality/getPlayerByName"
	PlayerLocality_Signup_FullMethodName          = "/org.nethergames.social.rpc.PlayerLocality/signup"
	PlayerLocality_Heartbeat_FullMethodName       = "/org.nethergames.social.rpc.PlayerLocality/heartbeat"
	PlayerLocality_Shutdown_FullMethodName        = "/org.nethergames.social.rpc.PlayerLocality/shutdown"
	PlayerLocality_GetAll_FullMethodName          = "/org.nethergames.social.rpc.PlayerLocality/getAll"
	PlayerLocality_GetState_FullMethodName        = "/org.nethergames.social.rpc.PlayerLocality/getState"
	PlayerLocality_GetPlayerEvents_FullMethodName = "/org.nethergames.social.rpc.PlayerLocality/getPlayerEvents"
)

// PlayerLocalityClient is the client API for PlayerLocality service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerLocalityClient interface {
	AddPlayer(ctx context.Context, in *AddPlayer, opts ...grpc.CallOption) (*ActionResponse, error)
	RemovePlayer(ctx context.Context, in *RemovePlayer, opts ...grpc.CallOption) (*ActionResponse, error)
	UpdatePlayer(ctx context.Context, in *UpdatePlayerStatus, opts ...grpc.CallOption) (*ActionResponse, error)
	GetPlayer(ctx context.Context, in *GetPlayerStatus, opts ...grpc.CallOption) (*PlayerStatusResponse, error)
	GetPlayerByXuid(ctx context.Context, in *GetPlayerStatus, opts ...grpc.CallOption) (*PlayerStatusResponse, error)
	GetPlayerByName(ctx context.Context, in *GetPlayerStatus, opts ...grpc.CallOption) (*PlayerStatusResponse, error)
	Signup(ctx context.Context, in *Signup, opts ...grpc.CallOption) (*SignupResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatMessage, opts ...grpc.CallOption) (*ActionResponse, error)
	Shutdown(ctx context.Context, in *Shutdown, opts ...grpc.CallOption) (*ActionResponse, error)
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllResponse, error)
	GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetStateResponse], error)
	// Leave/join events.
	GetPlayerEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerEvent], error)
}

type playerLocalityClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerLocalityClient(cc grpc.ClientConnInterface) PlayerLocalityClient {
	return &playerLocalityClient{cc}
}

func (c *playerLocalityClient) AddPlayer(ctx context.Context, in *AddPlayer, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_AddPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) RemovePlayer(ctx context.Context, in *RemovePlayer, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_RemovePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) UpdatePlayer(ctx context.Context, in *UpdatePlayerStatus, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_UpdatePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) GetPlayer(ctx context.Context, in *GetPlayerStatus, opts ...grpc.CallOption) (*PlayerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStatusResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_GetPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) GetPlayerByXuid(ctx context.Context, in *GetPlayerStatus, opts ...grpc.CallOption) (*PlayerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStatusResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_GetPlayerByXuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) GetPlayerByName(ctx context.Context, in *GetPlayerStatus, opts ...grpc.CallOption) (*PlayerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStatusResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_GetPlayerByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) Signup(ctx context.Context, in *Signup, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) Heartbeat(ctx context.Context, in *HeartbeatMessage, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) Shutdown(ctx context.Context, in *Shutdown, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, PlayerLocality_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerLocalityClient) GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetStateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerLocality_ServiceDesc.Streams[0], PlayerLocality_GetState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, GetStateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerLocality_GetStateClient = grpc.ServerStreamingClient[GetStateResponse]

func (c *playerLocalityClient) GetPlayerEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerLocality_ServiceDesc.Streams[1], PlayerLocality_GetPlayerEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, PlayerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerLocality_GetPlayerEventsClient = grpc.ServerStreamingClient[PlayerEvent]

// PlayerLocalityServer is the server API for PlayerLocality service.
// All implementations must embed UnimplementedPlayerLocalityServer
// for forward compatibility.
type PlayerLocalityServer interface {
	AddPlayer(context.Context, *AddPlayer) (*ActionResponse, error)
	RemovePlayer(context.Context, *RemovePlayer) (*ActionResponse, error)
	UpdatePlayer(context.Context, *UpdatePlayerStatus) (*ActionResponse, error)
	GetPlayer(context.Context, *GetPlayerStatus) (*PlayerStatusResponse, error)
	GetPlayerByXuid(context.Context, *GetPlayerStatus) (*PlayerStatusResponse, error)
	GetPlayerByName(context.Context, *GetPlayerStatus) (*PlayerStatusResponse, error)
	Signup(context.Context, *Signup) (*SignupResponse, error)
	Heartbeat(context.Context, *HeartbeatMessage) (*ActionResponse, error)
	Shutdown(context.Context, *Shutdown) (*ActionResponse, error)
	GetAll(context.Context, *Empty) (*GetAllResponse, error)
	GetState(*Empty, grpc.ServerStreamingServer[GetStateResponse]) error
	// Leave/join events.
	GetPlayerEvents(*Empty, grpc.ServerStreamingServer[PlayerEvent]) error
	mustEmbedUnimplementedPlayerLocalityServer()
}

// UnimplementedPlayerLocalityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerLocalityServer struct{}

func (UnimplementedPlayerLocalityServer) AddPlayer(context.Context, *AddPlayer) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlayer not implemented")
}
func (UnimplementedPlayerLocalityServer) RemovePlayer(context.Context, *RemovePlayer) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePlayer not implemented")
}
func (UnimplementedPlayerLocalityServer) UpdatePlayer(context.Context, *UpdatePlayerStatus) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlayer not implemented")
}
func (UnimplementedPlayerLocalityServer) GetPlayer(context.Context, *GetPlayerStatus) (*PlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayer not implemented")
}
func (UnimplementedPlayerLocalityServer) GetPlayerByXuid(context.Context, *GetPlayerStatus) (*PlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerByXuid not implemented")
}
func (UnimplementedPlayerLocalityServer) GetPlayerByName(context.Context, *GetPlayerStatus) (*PlayerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerByName not implemented")
}
func (UnimplementedPlayerLocalityServer) Signup(context.Context, *Signup) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedPlayerLocalityServer) Heartbeat(context.Context, *HeartbeatMessage) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPlayerLocalityServer) Shutdown(context.Context, *Shutdown) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPlayerLocalityServer) GetAll(context.Context, *Empty) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedPlayerLocalityServer) GetState(*Empty, grpc.ServerStreamingServer[GetStateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedPlayerLocalityServer) GetPlayerEvents(*Empty, grpc.ServerStreamingServer[PlayerEvent]) error {
	return status.Errorf(codes.Unimplemented, "method GetPlayerEvents not implemented")
}
func (UnimplementedPlayerLocalityServer) mustEmbedUnimplementedPlayerLocalityServer() {}
func (UnimplementedPlayerLocalityServer) testEmbeddedByValue()                        {}

// UnsafePlayerLocalityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerLocalityServer will
// result in compilation errors.
type UnsafePlayerLocalityServer interface {
	mustEmbedUnimplementedPlayerLocalityServer()
}

func RegisterPlayerLocalityServer(s grpc.ServiceRegistrar, srv PlayerLocalityServer) {
	// If the following call pancis, it indicates UnimplementedPlayerLocalityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerLocality_ServiceDesc, srv)
}

func _PlayerLocality_AddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).AddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_AddPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).AddPlayer(ctx, req.(*AddPlayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_RemovePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePlayer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).RemovePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_RemovePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).RemovePlayer(ctx, req.(*RemovePlayer))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_UpdatePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).UpdatePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_UpdatePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).UpdatePlayer(ctx, req.(*UpdatePlayerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_GetPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_GetPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).GetPlayer(ctx, req.(*GetPlayerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_GetPlayerByXuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).GetPlayerByXuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_GetPlayerByXuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).GetPlayerByXuid(ctx, req.(*GetPlayerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_GetPlayerByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).GetPlayerByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_GetPlayerByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).GetPlayerByName(ctx, req.(*GetPlayerStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Signup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).Signup(ctx, req.(*Signup))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).Heartbeat(ctx, req.(*HeartbeatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Shutdown)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).Shutdown(ctx, req.(*Shutdown))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerLocalityServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerLocality_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerLocalityServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerLocality_GetState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerLocalityServer).GetState(m, &grpc.GenericServerStream[Empty, GetStateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerLocality_GetStateServer = grpc.ServerStreamingServer[GetStateResponse]

func _PlayerLocality_GetPlayerEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerLocalityServer).GetPlayerEvents(m, &grpc.GenericServerStream[Empty, PlayerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerLocality_GetPlayerEventsServer = grpc.ServerStreamingServer[PlayerEvent]

// PlayerLocality_ServiceDesc is the grpc.ServiceDesc for PlayerLocality service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerLocality_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.nethergames.social.rpc.PlayerLocality",
	HandlerType: (*PlayerLocalityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addPlayer",
			Handler:    _PlayerLocality_AddPlayer_Handler,
		},
		{
			MethodName: "removePlayer",
			Handler:    _PlayerLocality_RemovePlayer_Handler,
		},
		{
			MethodName: "updatePlayer",
			Handler:    _PlayerLocality_UpdatePlayer_Handler,
		},
		{
			MethodName: "getPlayer",
			Handler:    _PlayerLocality_GetPlayer_Handler,
		},
		{
			MethodName: "getPlayerByXuid",
			Handler:    _PlayerLocality_GetPlayerByXuid_Handler,
		},
		{
			MethodName: "getPlayerByName",
			Handler:    _PlayerLocality_GetPlayerByName_Handler,
		},
		{
			MethodName: "signup",
			Handler:    _PlayerLocality_Signup_Handler,
		},
		{
			MethodName: "heartbeat",
			Handler:    _PlayerLocality_Heartbeat_Handler,
		},
		{
			MethodName: "shutdown",
			Handler:    _PlayerLocality_Shutdown_Handler,
		},
		{
			MethodName: "getAll",
			Handler:    _PlayerLocality_GetAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getState",
			Handler:       _PlayerLocality_GetState_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getPlayerEvents",
			Handler:       _PlayerLocality_GetPlayerEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "locater.proto",
}
