// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.4
// source: social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocialService_CreateParty_FullMethodName             = "/org.nethergames.social.rpc.SocialService/createParty"
	SocialService_DisbandParty_FullMethodName            = "/org.nethergames.social.rpc.SocialService/disbandParty"
	SocialService_KickMember_FullMethodName              = "/org.nethergames.social.rpc.SocialService/kickMember"
	SocialService_InviteMember_FullMethodName            = "/org.nethergames.social.rpc.SocialService/inviteMember"
	SocialService_GetPartyMembers_FullMethodName         = "/org.nethergames.social.rpc.SocialService/getPartyMembers"
	SocialService_GetParty_FullMethodName                = "/org.nethergames.social.rpc.SocialService/getParty"
	SocialService_GetPartyInvites_FullMethodName         = "/org.nethergames.social.rpc.SocialService/getPartyInvites"
	SocialService_DeclineInvite_FullMethodName           = "/org.nethergames.social.rpc.SocialService/declineInvite"
	SocialService_AcceptInvite_FullMethodName            = "/org.nethergames.social.rpc.SocialService/acceptInvite"
	SocialService_GetPlayerPartyInvites_FullMethodName   = "/org.nethergames.social.rpc.SocialService/getPlayerPartyInvites"
	SocialService_UpdatePartyPlayerStatus_FullMethodName = "/org.nethergames.social.rpc.SocialService/updatePartyPlayerStatus"
	SocialService_LeaveParty_FullMethodName              = "/org.nethergames.social.rpc.SocialService/leaveParty"
	SocialService_JoinPublicParty_FullMethodName         = "/org.nethergames.social.rpc.SocialService/joinPublicParty"
	SocialService_GetPlayerParty_FullMethodName          = "/org.nethergames.social.rpc.SocialService/getPlayerParty"
	SocialService_GetPublicParties_FullMethodName        = "/org.nethergames.social.rpc.SocialService/getPublicParties"
)

// SocialServiceClient is the client API for SocialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialServiceClient interface {
	CreateParty(ctx context.Context, in *PartyCreateRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	DisbandParty(ctx context.Context, in *PartyDisbandRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	KickMember(ctx context.Context, in *PartyKickRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	InviteMember(ctx context.Context, in *PartyInviteRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	GetPartyMembers(ctx context.Context, in *GetPartyMemberRequest, opts ...grpc.CallOption) (*GetPartyMemberResponse, error)
	GetParty(ctx context.Context, in *GetPartyRequest, opts ...grpc.CallOption) (*GetPartyResponse, error)
	GetPartyInvites(ctx context.Context, in *GetPartyInvitesRequest, opts ...grpc.CallOption) (*GetPartyInvitesResponse, error)
	DeclineInvite(ctx context.Context, in *PartyInvite, opts ...grpc.CallOption) (*PartyActionResponse, error)
	AcceptInvite(ctx context.Context, in *PartyInvite, opts ...grpc.CallOption) (*PartyActionResponse, error)
	GetPlayerPartyInvites(ctx context.Context, in *GetPlayerPartyInvitesRequest, opts ...grpc.CallOption) (*GetPartyInvitesResponse, error)
	UpdatePartyPlayerStatus(ctx context.Context, in *UpdatePlayerPartyStatusRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	LeaveParty(ctx context.Context, in *LeavePartyRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	JoinPublicParty(ctx context.Context, in *JoinPublicPartyRequest, opts ...grpc.CallOption) (*PartyActionResponse, error)
	// Endpoints that are not bound to players - mainly for admin / internal
	GetPlayerParty(ctx context.Context, in *GetPlayerPartyRequest, opts ...grpc.CallOption) (*GetPlayerPartyResponse, error)
	GetPublicParties(ctx context.Context, in *ListPublicPartiesRequest, opts ...grpc.CallOption) (*ListPublicPartiesResponse, error)
}

type socialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialServiceClient(cc grpc.ClientConnInterface) SocialServiceClient {
	return &socialServiceClient{cc}
}

func (c *socialServiceClient) CreateParty(ctx context.Context, in *PartyCreateRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_CreateParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) DisbandParty(ctx context.Context, in *PartyDisbandRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_DisbandParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) KickMember(ctx context.Context, in *PartyKickRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_KickMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) InviteMember(ctx context.Context, in *PartyInviteRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetPartyMembers(ctx context.Context, in *GetPartyMemberRequest, opts ...grpc.CallOption) (*GetPartyMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartyMemberResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPartyMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetParty(ctx context.Context, in *GetPartyRequest, opts ...grpc.CallOption) (*GetPartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartyResponse)
	err := c.cc.Invoke(ctx, SocialService_GetParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetPartyInvites(ctx context.Context, in *GetPartyInvitesRequest, opts ...grpc.CallOption) (*GetPartyInvitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartyInvitesResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPartyInvites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) DeclineInvite(ctx context.Context, in *PartyInvite, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_DeclineInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) AcceptInvite(ctx context.Context, in *PartyInvite, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_AcceptInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetPlayerPartyInvites(ctx context.Context, in *GetPlayerPartyInvitesRequest, opts ...grpc.CallOption) (*GetPartyInvitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartyInvitesResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPlayerPartyInvites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) UpdatePartyPlayerStatus(ctx context.Context, in *UpdatePlayerPartyStatusRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_UpdatePartyPlayerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) LeaveParty(ctx context.Context, in *LeavePartyRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_LeaveParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) JoinPublicParty(ctx context.Context, in *JoinPublicPartyRequest, opts ...grpc.CallOption) (*PartyActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartyActionResponse)
	err := c.cc.Invoke(ctx, SocialService_JoinPublicParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetPlayerParty(ctx context.Context, in *GetPlayerPartyRequest, opts ...grpc.CallOption) (*GetPlayerPartyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlayerPartyResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPlayerParty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialServiceClient) GetPublicParties(ctx context.Context, in *ListPublicPartiesRequest, opts ...grpc.CallOption) (*ListPublicPartiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicPartiesResponse)
	err := c.cc.Invoke(ctx, SocialService_GetPublicParties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServiceServer is the server API for SocialService service.
// All implementations must embed UnimplementedSocialServiceServer
// for forward compatibility.
type SocialServiceServer interface {
	CreateParty(context.Context, *PartyCreateRequest) (*PartyActionResponse, error)
	DisbandParty(context.Context, *PartyDisbandRequest) (*PartyActionResponse, error)
	KickMember(context.Context, *PartyKickRequest) (*PartyActionResponse, error)
	InviteMember(context.Context, *PartyInviteRequest) (*PartyActionResponse, error)
	GetPartyMembers(context.Context, *GetPartyMemberRequest) (*GetPartyMemberResponse, error)
	GetParty(context.Context, *GetPartyRequest) (*GetPartyResponse, error)
	GetPartyInvites(context.Context, *GetPartyInvitesRequest) (*GetPartyInvitesResponse, error)
	DeclineInvite(context.Context, *PartyInvite) (*PartyActionResponse, error)
	AcceptInvite(context.Context, *PartyInvite) (*PartyActionResponse, error)
	GetPlayerPartyInvites(context.Context, *GetPlayerPartyInvitesRequest) (*GetPartyInvitesResponse, error)
	UpdatePartyPlayerStatus(context.Context, *UpdatePlayerPartyStatusRequest) (*PartyActionResponse, error)
	LeaveParty(context.Context, *LeavePartyRequest) (*PartyActionResponse, error)
	JoinPublicParty(context.Context, *JoinPublicPartyRequest) (*PartyActionResponse, error)
	// Endpoints that are not bound to players - mainly for admin / internal
	GetPlayerParty(context.Context, *GetPlayerPartyRequest) (*GetPlayerPartyResponse, error)
	GetPublicParties(context.Context, *ListPublicPartiesRequest) (*ListPublicPartiesResponse, error)
	mustEmbedUnimplementedSocialServiceServer()
}

// UnimplementedSocialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServiceServer struct{}

func (UnimplementedSocialServiceServer) CreateParty(context.Context, *PartyCreateRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateParty not implemented")
}
func (UnimplementedSocialServiceServer) DisbandParty(context.Context, *PartyDisbandRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisbandParty not implemented")
}
func (UnimplementedSocialServiceServer) KickMember(context.Context, *PartyKickRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickMember not implemented")
}
func (UnimplementedSocialServiceServer) InviteMember(context.Context, *PartyInviteRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedSocialServiceServer) GetPartyMembers(context.Context, *GetPartyMemberRequest) (*GetPartyMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartyMembers not implemented")
}
func (UnimplementedSocialServiceServer) GetParty(context.Context, *GetPartyRequest) (*GetPartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParty not implemented")
}
func (UnimplementedSocialServiceServer) GetPartyInvites(context.Context, *GetPartyInvitesRequest) (*GetPartyInvitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPartyInvites not implemented")
}
func (UnimplementedSocialServiceServer) DeclineInvite(context.Context, *PartyInvite) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclineInvite not implemented")
}
func (UnimplementedSocialServiceServer) AcceptInvite(context.Context, *PartyInvite) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptInvite not implemented")
}
func (UnimplementedSocialServiceServer) GetPlayerPartyInvites(context.Context, *GetPlayerPartyInvitesRequest) (*GetPartyInvitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerPartyInvites not implemented")
}
func (UnimplementedSocialServiceServer) UpdatePartyPlayerStatus(context.Context, *UpdatePlayerPartyStatusRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePartyPlayerStatus not implemented")
}
func (UnimplementedSocialServiceServer) LeaveParty(context.Context, *LeavePartyRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveParty not implemented")
}
func (UnimplementedSocialServiceServer) JoinPublicParty(context.Context, *JoinPublicPartyRequest) (*PartyActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinPublicParty not implemented")
}
func (UnimplementedSocialServiceServer) GetPlayerParty(context.Context, *GetPlayerPartyRequest) (*GetPlayerPartyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerParty not implemented")
}
func (UnimplementedSocialServiceServer) GetPublicParties(context.Context, *ListPublicPartiesRequest) (*ListPublicPartiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicParties not implemented")
}
func (UnimplementedSocialServiceServer) mustEmbedUnimplementedSocialServiceServer() {}
func (UnimplementedSocialServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServiceServer will
// result in compilation errors.
type UnsafeSocialServiceServer interface {
	mustEmbedUnimplementedSocialServiceServer()
}

func RegisterSocialServiceServer(s grpc.ServiceRegistrar, srv SocialServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocialService_ServiceDesc, srv)
}

func _SocialService_CreateParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).CreateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_CreateParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).CreateParty(ctx, req.(*PartyCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_DisbandParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyDisbandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).DisbandParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_DisbandParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).DisbandParty(ctx, req.(*PartyDisbandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_KickMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyKickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).KickMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_KickMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).KickMember(ctx, req.(*PartyKickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).InviteMember(ctx, req.(*PartyInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetPartyMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartyMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPartyMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPartyMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPartyMembers(ctx, req.(*GetPartyMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetParty(ctx, req.(*GetPartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetPartyInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartyInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPartyInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPartyInvites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPartyInvites(ctx, req.(*GetPartyInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_DeclineInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyInvite)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).DeclineInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_DeclineInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).DeclineInvite(ctx, req.(*PartyInvite))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_AcceptInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyInvite)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).AcceptInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_AcceptInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).AcceptInvite(ctx, req.(*PartyInvite))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetPlayerPartyInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerPartyInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPlayerPartyInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPlayerPartyInvites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPlayerPartyInvites(ctx, req.(*GetPlayerPartyInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_UpdatePartyPlayerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerPartyStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).UpdatePartyPlayerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_UpdatePartyPlayerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).UpdatePartyPlayerStatus(ctx, req.(*UpdatePlayerPartyStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_LeaveParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeavePartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).LeaveParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_LeaveParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).LeaveParty(ctx, req.(*LeavePartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_JoinPublicParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPublicPartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).JoinPublicParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_JoinPublicParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).JoinPublicParty(ctx, req.(*JoinPublicPartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetPlayerParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerPartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPlayerParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPlayerParty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPlayerParty(ctx, req.(*GetPlayerPartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialService_GetPublicParties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicPartiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServiceServer).GetPublicParties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialService_GetPublicParties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServiceServer).GetPublicParties(ctx, req.(*ListPublicPartiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialService_ServiceDesc is the grpc.ServiceDesc for SocialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.nethergames.social.rpc.SocialService",
	HandlerType: (*SocialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createParty",
			Handler:    _SocialService_CreateParty_Handler,
		},
		{
			MethodName: "disbandParty",
			Handler:    _SocialService_DisbandParty_Handler,
		},
		{
			MethodName: "kickMember",
			Handler:    _SocialService_KickMember_Handler,
		},
		{
			MethodName: "inviteMember",
			Handler:    _SocialService_InviteMember_Handler,
		},
		{
			MethodName: "getPartyMembers",
			Handler:    _SocialService_GetPartyMembers_Handler,
		},
		{
			MethodName: "getParty",
			Handler:    _SocialService_GetParty_Handler,
		},
		{
			MethodName: "getPartyInvites",
			Handler:    _SocialService_GetPartyInvites_Handler,
		},
		{
			MethodName: "declineInvite",
			Handler:    _SocialService_DeclineInvite_Handler,
		},
		{
			MethodName: "acceptInvite",
			Handler:    _SocialService_AcceptInvite_Handler,
		},
		{
			MethodName: "getPlayerPartyInvites",
			Handler:    _SocialService_GetPlayerPartyInvites_Handler,
		},
		{
			MethodName: "updatePartyPlayerStatus",
			Handler:    _SocialService_UpdatePartyPlayerStatus_Handler,
		},
		{
			MethodName: "leaveParty",
			Handler:    _SocialService_LeaveParty_Handler,
		},
		{
			MethodName: "joinPublicParty",
			Handler:    _SocialService_JoinPublicParty_Handler,
		},
		{
			MethodName: "getPlayerParty",
			Handler:    _SocialService_GetPlayerParty_Handler,
		},
		{
			MethodName: "getPublicParties",
			Handler:    _SocialService_GetPublicParties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}
